// AUTO-GENERATED by scripts/ingest-emails.mjs
// Source: data/synthetic-test-emails.mbox
// Generated: 2026-05-02T07:27:18.477Z
// Threads kept: 10 of 11 parsed (1 filtered out)
// Approx tokens: 2484 (budget 25000)
// Over-budget: false
//
// Phase 2 status: NOT YET WIRED into Neela's system prompt. The corpus is
// generated and committed for inspection / future use. To enable, add an
// import + cache_control block in api/neela.ts (note: Anthropic max is 4
// breakpoints; one of the existing blocks would need to merge).
//
// Token-budget plan: when EMAIL_CORPUS_OVER_BUDGET = true, switch to a
// vector-retrieval path (Voyage AI embed + Cloudflare Vectorize index).

export interface EmailKeyExchange {
	q: string;
	a: string;
}

export interface EmailCorpusEntry {
	thread_id: string;
	subject: string;
	topic: string;
	summary: string;
	key_exchange: EmailKeyExchange;
}

export const EMAIL_CORPUS: EmailCorpusEntry[] = [
	{
		"thread_id": "mbox-0",
		"subject": "Wedding for 250 in August - need quote",
		"topic": "Wedding for 250 in August - need quote",
		"summary": "User asked about: Hi there! My partner and I are getting married on August 15, 2026 at the UBC Boathouse and we'd love to talk about catering. We're expecting around 250 guests. …",
		"key_exchange": {
			"q": "Hi there! My partner and I are getting married on August 15, 2026 at the UBC Boathouse and we'd love to talk about catering. We're expecting around 250 guests. Mostly halal, around 30% vegetarian, a few Jain guests on my side. Could we set up a tasting? My number is [phone] and we're at [address], Vancouver. Looking fo",
			"a": "Hi Priya, congratulations! 250 at UBC Boathouse in August sounds wonderful, we've catered several weddings there. For a guest count and dietary mix like yours, I'd suggest looking at our Family Style 3 menu ($60/guest) or one of the upper wedding tiers. Halal is standard for us, all our chicken and lamb is halal-certif"
		}
	},
	{
		"thread_id": "mbox-1",
		"subject": "Office lunch tomorrow possible??",
		"topic": "Office lunch tomorrow possible??",
		"summary": "User asked about: Hi - really sorry for short notice but our usual caterer just bailed on us for tomorrow, Tuesday April 13, 12:30pm delivery. We have 35 people in our Burrard St…",
		"key_exchange": {
			"q": "Hi - really sorry for short notice but our usual caterer just bailed on us for tomorrow, Tuesday April 13, 12:30pm delivery. We have 35 people in our Burrard St office, [address] 14th floor, downtown Vancouver. Half veg, half not, no nut allergies. Budget around $30/head. Please let me know if anything can be done. [ph",
			"a": "Hey Devon, we can absolutely make tomorrow work for 35 at 12:30. I'd recommend Option 2 ($25.95/guest) which is 2 veg + 2 non-veg curries with naan, basmati rice, chutneys. Veg sides are clearly labeled. Total food before tax for 35 is around $908. Add $5 delivery (you're 0-10km from us) and $0.50/person disposable cut"
		}
	},
	{
		"thread_id": "mbox-2",
		"subject": "Halal-only menu for sangeet next month",
		"topic": "Halal-only menu for sangeet next month",
		"summary": "User asked about: Asalam alaikum, I'm planning a sangeet for my brother on May 10 at our home in Surrey (16280 88 Avenue). Approx 80 guests, all halal please, no alcohol on premi…",
		"key_exchange": {
			"q": "Asalam alaikum, I'm planning a sangeet for my brother on May 10 at our home in Surrey (16280 88 Avenue). Approx 80 guests, all halal please, no alcohol on premises. Can you confirm everything is halal-certified, not just the meat? I want to be sure about the kitchen too. Number: [phone].",
			"a": "Walaikum asalam Aliyah, congratulations to your brother. Yes, Sula has been a halal-certified kitchen since we opened in 2010, all chicken and lamb is sourced from halal-certified BC suppliers and we don't keep pork or alcohol on the premises in our kitchens. For the home sangeet, May 10 is open. 80 guests we'd typical"
		}
	},
	{
		"thread_id": "mbox-3",
		"subject": "Need to cancel May 22 booking - basement flood",
		"topic": "Need to cancel May 22 booking - basement flood",
		"summary": "User asked about: Hi, this is Marc, I had a 60-person dinner booked for May 22 (next Friday), reference SULA-2026-0419-MT. Our basement flooded yesterday and we have to cancel th…",
		"key_exchange": {
			"q": "Hi, this is Marc, I had a 60-person dinner booked for May 22 (next Friday), reference SULA-2026-0419-MT. Our basement flooded yesterday and we have to cancel the whole event, contractors will be in for weeks. What's the situation with the deposit? I know we're inside the cancellation window. Anything we can do?",
			"a": "Hi Marc, sorry to hear about the flood, that's stressful. Let me pull your file. You're right that May 22 is inside the standard cancellation window (we ask for 14 days notice for full refund), but given the circumstances we can hold your deposit as credit toward a future booking within 12 months. That way you don't lo"
		}
	},
	{
		"thread_id": "mbox-4",
		"subject": "4th time ordering - any chance of a recurring rate?",
		"topic": "4th time ordering - any chance of a recurring rate?",
		"summary": "User asked about: Hi, we've ordered from you 3 times in the past 6 months for our team lunches, always great. We're planning to set up a recurring monthly Indian lunch (12:30, ar…",
		"key_exchange": {
			"q": "Hi, we've ordered from you 3 times in the past 6 months for our team lunches, always great. We're planning to set up a recurring monthly Indian lunch (12:30, around 45 people, our office at [address]). Any chance of a small discount for committing to 12 months? Happy to lock in the same menu rotation. Card on file is [",
			"a": "Hi Jasmine, we love repeat corporate clients, thanks for the consistent business. For 12-month commitments at 45 guests/month, we can absolutely set up an invoiced arrangement and offer a small loyalty discount, typically 5-8% off the per-guest rate depending on tier locked in. Net-15 invoicing standard, monthly billin"
		}
	},
	{
		"thread_id": "mbox-5",
		"subject": "Outdoor wedding July - rain plan question",
		"topic": "Outdoor wedding July - rain plan question",
		"summary": "User asked about: Hey, planning an outdoor wedding July 11 at Stanley Park's Brockton Pavilion area. 180 guests. Mostly Indian crowd, mixed dietary. My main worry is the weather …",
		"key_exchange": {
			"q": "Hey, planning an outdoor wedding July 11 at Stanley Park's Brockton Pavilion area. 180 guests. Mostly Indian crowd, mixed dietary. My main worry is the weather - what's your contingency if it rains hard? Do you bring tents or do we need to handle that? Also asking about transport time, the venue is a bit far from your ",
			"a": "Hi Sam, Brockton Pavilion is great, we've done a few weddings out there. On rain contingency: we recommend you (or your event coordinator) handle the tent rental directly since it's part of the venue setup, not catering. We're happy to recommend partners we've worked with there. Our heated stainless or hammered copper "
		}
	},
	{
		"thread_id": "mbox-6",
		"subject": "Strict Jain menu request",
		"topic": "Strict Jain menu request",
		"summary": "User asked about: Hello, do you do Jain catering? I'm planning a small lunch for 25 (April 30) where about 8 of the guests are strict Jain. Can you handle separate prep, no onion…",
		"key_exchange": {
			"q": "Hello, do you do Jain catering? I'm planning a small lunch for 25 (April 30) where about 8 of the guests are strict Jain. Can you handle separate prep, no onion/garlic/root vegetables for them? Some are also avoiding eggplant. Reach me at [phone].",
			"a": "Hi Rakesh, yes we do. We have dedicated prep areas for Jain (no onion, no garlic, no root vegetables, no honey, eggplant excluded on request). For 8 strict Jain guests within a 25-person lunch we'd prepare a small parallel menu in separate trays so they're not pulling from the shared dishes. April 30 is open. Want me t"
		}
	},
	{
		"thread_id": "mbox-7",
		"subject": "Tasting for September wedding?",
		"topic": "Tasting for September wedding?",
		"summary": "User asked about: Hi! Booking my September 12 wedding caterer this month. About 200 guests, vegetarian-heavy. Before I commit, would love to come in for a tasting. Is that someth…",
		"key_exchange": {
			"q": "Hi! Booking my September 12 wedding caterer this month. About 200 guests, vegetarian-heavy. Before I commit, would love to come in for a tasting. Is that something you offer pre-booking, or only after deposit? My phone is [phone].",
			"a": "Hi Asha, congrats! Yes, we offer pre-booking tastings for weddings. There's a small fee ($75/couple) which gets fully credited to your final invoice when you book. We do them at our Commercial Drive location, usually Tuesday or Wednesday evenings. Vegetarian-heavy menus are no problem, we'll set up an Option 3 or weddi"
		}
	},
	{
		"thread_id": "mbox-8",
		"subject": "URGENT: Menu change for Saturday event",
		"topic": "URGENT: Menu change for Saturday event",
		"summary": "User asked about: Hi, we have an event this Saturday June 6 (60 people) and I just realized we forgot to flag a severe shellfish allergy. The booking has the standard menu - can …",
		"key_exchange": {
			"q": "Hi, we have an event this Saturday June 6 (60 people) and I just realized we forgot to flag a severe shellfish allergy. The booking has the standard menu - can we swap any items that might cross-contaminate? Booking ref SULA-2026-0518-EM. Phone: [phone].",
			"a": "Hi Elena, no problem, plenty of time to handle this safely. Sula's main kitchen doesn't actually use shellfish in any standard menu, our protein is chicken, lamb, paneer, and vegetables only. For severe shellfish allergy specifically we're a low-risk environment compared to most kitchens. Two precautions we'll add at n"
		}
	},
	{
		"thread_id": "mbox-9",
		"subject": "Catering for memorial service",
		"topic": "Catering for memorial service",
		"summary": "User asked about: Hello, I'm reaching out on behalf of our family. We're holding a memorial service for my mother on May 1 and need catering for approximately 90 people at our ho…",
		"key_exchange": {
			"q": "Hello, I'm reaching out on behalf of our family. We're holding a memorial service for my mother on May 1 and need catering for approximately 90 people at our home in North Vancouver ([address]). She loved Sula, so we'd really like to honour her with your food. Mostly traditional South Indian dishes if possible. Could y",
			"a": "Thomas, I'm so sorry for your loss, and thank you for thinking of us at this time. We'd be honoured to help. For 90 guests with South Indian focus, we can build a custom menu pulling from our Hyderabadi and South Indian traditions, dishes like Chicken Chettinad, Hyderabadi Biryani, Coconut Vegetable Curry, Lemon Rice, "
		}
	}
];

export const EMAIL_CORPUS_THREAD_COUNT = 10;
export const EMAIL_CORPUS_TOKEN_ESTIMATE = 2484;
export const EMAIL_CORPUS_OVER_BUDGET = false;
export const EMAIL_CORPUS_GENERATED_AT = "2026-05-02T07:27:18.477Z";
