// AUTO-GENERATED by scripts/ingest-emails.mjs
// Source: data/synthetic-test-emails.json
// Generated: 2026-05-02T06:58:14.692Z
// Threads kept: 9 of 10 parsed (1 filtered out)
// Approx tokens: 2069
//
// Phase 2 status: NOT YET WIRED into Neela's system prompt. The corpus is
// generated and committed for inspection / future use. To enable, add an
// import + 5th cache_control block in api/neela.ts (note: Anthropic max is 4
// breakpoints, so one of the existing blocks would need to merge).
//
// Token-budget plan: if EMAIL_CORPUS_TOKEN_ESTIMATE > 30000 we'll instead
// pre-embed via Voyage AI and query a Cloudflare Vectorize index per chat.

export interface EmailCorpusEntry {
	thread_id: string;
	subject: string;
	topic: string;
	summary: string;
	exchange: string[];
}

export const EMAIL_CORPUS: EmailCorpusEntry[] = [
	{
		"thread_id": "syn-001-wedding-aug",
		"subject": "Wedding for 250 in August - need quote",
		"topic": "Wedding for 250 in August - need quote",
		"summary": "User asked about: Hi there! My partner and I are getting married on August 15, 2026 at the UBC Boathouse and we'd love to talk about catering. We're expecting around 250 guests. …",
		"exchange": [
			"USER: Hi there! My partner and I are getting married on August 15, 2026 at the UBC Boathouse and we'd love to talk about catering. We're expecting around 250 guests. Mostly halal, around 30% vegetarian, a few Jain guests on my side. Could we set up a tasting? My number is [phone]. Looking forward to hearing back. Thanks, Pri",
			"SULA: Hi Priya, congratulations! 250 at UBC Boathouse in August sounds wonderful, we've catered several weddings there. For a guest count and dietary mix like yours, I'd suggest looking at our Family Style 3 menu ($60/guest) or one of the upper wedding tiers. Halal is standard for us, all our chicken and lamb is halal-certif"
		]
	},
	{
		"thread_id": "syn-002-office-tomorrow",
		"subject": "Office lunch tomorrow possible??",
		"topic": "Office lunch tomorrow possible??",
		"summary": "User asked about: Hi - really sorry for short notice but our usual caterer just bailed on us for tomorrow, Tuesday April 13, 12:30pm delivery. We have [address] office, [address]…",
		"exchange": [
			"USER: Hi - really sorry for short notice but our usual caterer just bailed on us for tomorrow, Tuesday April 13, 12:30pm delivery. We have [address] office, [address] 14th floor, downtown. Half veg, half not, no nut allergies. Budget around $30/head. Please let me know if anything can be done. [phone].",
			"SULA: Hey Devon, we can absolutely make tomorrow work for 35 at 12:30. I'd recommend Option 2 ($25.95/guest) which is 2 veg + 2 non-veg curries with naan, basmati rice, chutneys. Veg sides are clearly labeled. Total food before tax for 35 is around $908. Add $5 delivery (you're 0-10km from us) and $0.50/person disposable cut"
		]
	},
	{
		"thread_id": "syn-003-halal-sangeet",
		"subject": "Halal-only menu for sangeet next month",
		"topic": "Halal-only menu for sangeet next month",
		"summary": "User asked about: Asalam alaikum, I'm planning a sangeet for my brother on May 10 at our home in Surrey ([address]). Approx 80 guests, all halal please, no alcohol on premises. C…",
		"exchange": [
			"USER: Asalam alaikum, I'm planning a sangeet for my brother on May 10 at our home in Surrey ([address]). Approx 80 guests, all halal please, no alcohol on premises. Can you confirm everything is halal-certified, not just the meat? I want to be sure about the kitchen too. Number: [phone].",
			"SULA: Walaikum asalam Aliyah, congratulations to your brother. Yes, Sula has been a halal-certified kitchen since we opened in 2010, all chicken and lamb is sourced from halal-certified BC suppliers and we don't keep pork or alcohol on the premises in our kitchens. For the home sangeet, May 10 is open. 80 guests we'd typical"
		]
	},
	{
		"thread_id": "syn-004-cancel-flood",
		"subject": "Need to cancel May 22 booking - basement flood",
		"topic": "Need to cancel May 22 booking - basement flood",
		"summary": "User asked about: Hi, this is Marc, I had a 60-person dinner booked for May 22 (next Friday), reference SULA-2026-0419-MT. Our basement flooded yesterday and we have to cancel th…",
		"exchange": [
			"USER: Hi, this is Marc, I had a 60-person dinner booked for May 22 (next Friday), reference SULA-2026-0419-MT. Our basement flooded yesterday and we have to cancel the whole event, contractors will be in for weeks. What's the situation with the deposit? I know we're inside the cancellation window. Anything we can do?",
			"SULA: Hi Marc, sorry to hear about the flood, that's stressful. Let me pull your file. You're right that May 22 is inside the standard cancellation window (we ask for 14 days notice for full refund), but given the circumstances we can hold your deposit as credit toward a future booking within [address] you don't lose it and "
		]
	},
	{
		"thread_id": "syn-005-recurring-corp",
		"subject": "Pricing for repeat corporate booking - monthly?",
		"topic": "Pricing for repeat corporate booking - monthly?",
		"summary": "User asked about: Hi, we've ordered from you 3 times in the past 6 months for our team lunches, always great. We're planning to set up a recurring monthly Indian lunch (12:30, ar…",
		"exchange": [
			"USER: Hi, we've ordered from you 3 times in the past 6 months for our team lunches, always great. We're planning to set up a recurring monthly Indian lunch (12:30, around 45 people, our office at 555 W Hastings). Any chance of a small discount for committing to 12 months? Happy to lock in the same menu rotation. Card on file",
			"SULA: Hi Jasmine, we love repeat corporate clients, thanks for the consistent business. For 12-month commitments at 45 guests/month, we can absolutely set up an invoiced arrangement and offer a small loyalty discount, typically 5-8% off the per-guest rate depending on tier locked in. Net-15 invoicing standard, monthly billin"
		]
	},
	{
		"thread_id": "syn-006-jain-question",
		"subject": "Question about Jain menu",
		"topic": "Question about Jain menu",
		"summary": "User asked about: Hello, do you do Jain catering? I'm planning a small lunch for 25 (April 30) where about 8 of the guests are strict Jain. Can you handle separate prep, no onion…",
		"exchange": [
			"USER: Hello, do you do Jain catering? I'm planning a small lunch for 25 (April 30) where about 8 of the guests are strict Jain. Can you handle separate prep, no onion/garlic/root vegetables for them?",
			"SULA: Hi Rakesh, yes we do. We have dedicated prep areas for Jain (no onion, no garlic, no root vegetables, no honey). For 8 Jain guests within a 25-person lunch we'd prepare a small parallel menu in separate trays so they're not pulling from the shared dishes. April 30 is open. Quick question, are the 8 Jain guests strict o"
		]
	},
	{
		"thread_id": "syn-007-out-of-region",
		"subject": "Catering for Whistler retreat",
		"topic": "Catering for Whistler retreat",
		"summary": "User asked about: Hi, do you cater corporate retreats up in Whistler? We have one planned for July 18-19 at the Fairmont, around 60 people, both nights are dinners. Open to eithe…",
		"exchange": [
			"USER: Hi, do you cater corporate retreats up in Whistler? We have one planned for July 18-19 at the Fairmont, around 60 people, both nights are dinners. Open to either cocktail-style appetizer service or full sit-down.",
			"SULA: Hi Sam, thanks for thinking of us. Whistler is just outside our standard service area (we cover GVRD: Vancouver, Burnaby, Richmond, Surrey, North Van, West Van). For a Fairmont retreat we'd recommend a Whistler-based caterer who can do regular kitchen access, the logistics of a 2-day, 60-guest event 2 hours up the high"
		]
	},
	{
		"thread_id": "syn-008-thank-you-only",
		"subject": "Thanks!",
		"topic": "Thanks!",
		"summary": "User asked about: Just wanted to say thank you, the food at Saturday's event was incredible. Will book again.",
		"exchange": [
			"USER: Just wanted to say thank you, the food at Saturday's event was incredible. Will book again.",
			"SULA: Thanks Helen, glad you and your guests enjoyed it!"
		]
	},
	{
		"thread_id": "syn-009-allergy-detail",
		"subject": "Severe nut allergy - corporate lunch question",
		"topic": "Severe nut allergy - corporate lunch question",
		"summary": "User asked about: Hi, planning a 25-person lunch on May 7. One of our team members has a severe peanut and tree nut allergy (anaphylaxis-grade, carries an EpiPen). Can you guaran…",
		"exchange": [
			"USER: Hi, planning a 25-person lunch on May 7. One of our team members has a severe peanut and tree nut allergy (anaphylaxis-grade, carries an EpiPen). Can you guarantee a nut-free meal for her? Even cross-contamination?",
			"SULA: Hi Diana, I want to be straight with you because anaphylaxis is serious. We can absolutely prepare a nut-free meal in a separate prep area with separate utensils, BUT our kitchen does handle cashews (in some korma recipes) and almonds (in some desserts) for other dishes. For an anaphylaxis-grade allergy I always tell c"
		]
	}
];

export const EMAIL_CORPUS_THREAD_COUNT = 9;
export const EMAIL_CORPUS_TOKEN_ESTIMATE = 2069;
export const EMAIL_CORPUS_OVER_BUDGET = false;
export const EMAIL_CORPUS_GENERATED_AT = "2026-05-02T06:58:14.692Z";
